mysql:
   image: mysql:latest
   container_name: mysql
   environment:
     MYSQL_DATABASE: murano
     MYSQL_USER: mysql
     MYSQL_PASSWORD: mysql
     MYSQL_ROOT_PASSWORD: supersecret
rabbit:
   image: rabbitmq:3
   container_name: rabbit
murano:
  image: hmunfru/fiware-murano
  extra_hosts:
  - "murano.lab.fiware.org:127.0.0.1"
  ports:
   - 8082:8082
  links:
   - mysql
   - rabbit
  environment: 
     - PASSWORD
     - REVISION
murano-test:
  image: hmunfru/murano-test
  links:
   - murano
  environment:
   - PASSWORD
   - REVISION
